<?php
/**
 * SteinAPI Configuration
 * This file is auto-generated by the Home Assistant Add-on
 * Do not edit manually - changes will be overwritten
 */

// Configuration will be generated during startup
die('Configuration not yet generated. Please restart the add-on.');
